//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsClient.localhost {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool validateUser(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryAllEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QueryAllEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployeeByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteEmployeeByID(string EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OperateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int OperateEmployee(object[] param, int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalNextEmployeeCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CalNextEmployeeCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryEmployeeByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryEmployeeByName(string staffName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryCompanies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryCompanies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OperaCompanies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int OperaCompanies(object[] param, int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryGoods", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryGoods();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryGoodsByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryGoodsByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryGoodsByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryGoodsByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryGoodsByWarehouseID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryGoodsByWarehouseID(string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryAllProductInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryAllProductInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OperateProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int OperateProduct(object[] param, int op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalNextProductCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CalNextProductCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPurOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryPurOrder(string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPurNotInOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryPurNotInOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPurOrderByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryPurOrderByID(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OperatePurOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int OperatePurOrder(object[] param, int op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryWH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryWH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalNextPurchaseCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CalNextPurchaseCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calNextWarehousingCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string calNextWarehousingCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/operateWarehousingRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int operateWarehousingRecord(object[] param, int op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryWarehousing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QueryWarehousing(object[] param, int op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuerySaleOrders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QuerySaleOrders(string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OperateSaleOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int OperateSaleOrder(object[] param, int op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalNextSaleOrderCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string CalNextSaleOrderCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuerySaleNotOutOrders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet QuerySaleNotOutOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateTestData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void GenerateTestData();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WindowsClient.localhost.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WindowsClient.localhost.ServiceSoap>, WindowsClient.localhost.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public bool validateUser(string user, string pass) {
            return base.Channel.validateUser(user, pass);
        }
        
        public System.Data.DataSet QueryAllEmployee() {
            return base.Channel.QueryAllEmployee();
        }
        
        public int DeleteEmployeeByID(string EmployeeID) {
            return base.Channel.DeleteEmployeeByID(EmployeeID);
        }
        
        public int OperateEmployee(object[] param, int i) {
            return base.Channel.OperateEmployee(param, i);
        }
        
        public string CalNextEmployeeCode() {
            return base.Channel.CalNextEmployeeCode();
        }
        
        public System.Data.DataSet QueryEmployeeByName(string staffName) {
            return base.Channel.QueryEmployeeByName(staffName);
        }
        
        public System.Data.DataSet QueryCompanies() {
            return base.Channel.QueryCompanies();
        }
        
        public int OperaCompanies(object[] param, int i) {
            return base.Channel.OperaCompanies(param, i);
        }
        
        public System.Data.DataSet QueryGoods() {
            return base.Channel.QueryGoods();
        }
        
        public System.Data.DataSet QueryGoodsByCode(string code) {
            return base.Channel.QueryGoodsByCode(code);
        }
        
        public System.Data.DataSet QueryGoodsByName(string name) {
            return base.Channel.QueryGoodsByName(name);
        }
        
        public System.Data.DataSet QueryGoodsByWarehouseID(string param) {
            return base.Channel.QueryGoodsByWarehouseID(param);
        }
        
        public System.Data.DataSet QueryAllProductInfo() {
            return base.Channel.QueryAllProductInfo();
        }
        
        public int OperateProduct(object[] param, int op) {
            return base.Channel.OperateProduct(param, op);
        }
        
        public string CalNextProductCode() {
            return base.Channel.CalNextProductCode();
        }
        
        public System.Data.DataSet QueryPurOrder(string state) {
            return base.Channel.QueryPurOrder(state);
        }
        
        public System.Data.DataSet QueryPurNotInOrder() {
            return base.Channel.QueryPurNotInOrder();
        }
        
        public System.Data.DataSet QueryPurOrderByID(string orderId) {
            return base.Channel.QueryPurOrderByID(orderId);
        }
        
        public int OperatePurOrder(object[] param, int op) {
            return base.Channel.OperatePurOrder(param, op);
        }
        
        public System.Data.DataSet QueryWH() {
            return base.Channel.QueryWH();
        }
        
        public string CalNextPurchaseCode() {
            return base.Channel.CalNextPurchaseCode();
        }
        
        public string calNextWarehousingCode() {
            return base.Channel.calNextWarehousingCode();
        }
        
        public int operateWarehousingRecord(object[] param, int op) {
            return base.Channel.operateWarehousingRecord(param, op);
        }
        
        public System.Data.DataSet QueryWarehousing(object[] param, int op) {
            return base.Channel.QueryWarehousing(param, op);
        }
        
        public System.Data.DataSet QuerySaleOrders(string state) {
            return base.Channel.QuerySaleOrders(state);
        }
        
        public int OperateSaleOrder(object[] param, int op) {
            return base.Channel.OperateSaleOrder(param, op);
        }
        
        public string CalNextSaleOrderCode() {
            return base.Channel.CalNextSaleOrderCode();
        }
        
        public System.Data.DataSet QuerySaleNotOutOrders() {
            return base.Channel.QuerySaleNotOutOrders();
        }
        
        public void GenerateTestData() {
            base.Channel.GenerateTestData();
        }
    }
}
