//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.17929 版自动生成。
// 
#pragma warning disable 1591

namespace WindowsClient.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback validateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryAllEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteEmployeeByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback OperateEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalNextEmployeeCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryEmployeeByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryCompaniesOperationCompleted;
        
        private System.Threading.SendOrPostCallback OperaCompaniesOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryGoodsOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryGoodsByCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryGoodsByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryGoodsByWarehouseIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryAllProductInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback OperateProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalNextProductCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryPurOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryPurNotInOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryPurOrderByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback OperatePurOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryWHOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalNextPurchaseCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback calNextWarehousingCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback operateWarehousingRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryWarehousingOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerySaleOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback OperateSaleOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalNextSaleOrderCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerySaleNotOutOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateTestDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::WindowsClient.Properties.Settings.Default.WindowsClient_localhost_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event validateUserCompletedEventHandler validateUserCompleted;
        
        /// <remarks/>
        public event QueryAllEmployeeCompletedEventHandler QueryAllEmployeeCompleted;
        
        /// <remarks/>
        public event DeleteEmployeeByIDCompletedEventHandler DeleteEmployeeByIDCompleted;
        
        /// <remarks/>
        public event OperateEmployeeCompletedEventHandler OperateEmployeeCompleted;
        
        /// <remarks/>
        public event CalNextEmployeeCodeCompletedEventHandler CalNextEmployeeCodeCompleted;
        
        /// <remarks/>
        public event QueryEmployeeByNameCompletedEventHandler QueryEmployeeByNameCompleted;
        
        /// <remarks/>
        public event QueryCompaniesCompletedEventHandler QueryCompaniesCompleted;
        
        /// <remarks/>
        public event OperaCompaniesCompletedEventHandler OperaCompaniesCompleted;
        
        /// <remarks/>
        public event QueryGoodsCompletedEventHandler QueryGoodsCompleted;
        
        /// <remarks/>
        public event QueryGoodsByCodeCompletedEventHandler QueryGoodsByCodeCompleted;
        
        /// <remarks/>
        public event QueryGoodsByNameCompletedEventHandler QueryGoodsByNameCompleted;
        
        /// <remarks/>
        public event QueryGoodsByWarehouseIDCompletedEventHandler QueryGoodsByWarehouseIDCompleted;
        
        /// <remarks/>
        public event QueryAllProductInfoCompletedEventHandler QueryAllProductInfoCompleted;
        
        /// <remarks/>
        public event OperateProductCompletedEventHandler OperateProductCompleted;
        
        /// <remarks/>
        public event CalNextProductCodeCompletedEventHandler CalNextProductCodeCompleted;
        
        /// <remarks/>
        public event QueryPurOrderCompletedEventHandler QueryPurOrderCompleted;
        
        /// <remarks/>
        public event QueryPurNotInOrderCompletedEventHandler QueryPurNotInOrderCompleted;
        
        /// <remarks/>
        public event QueryPurOrderByIDCompletedEventHandler QueryPurOrderByIDCompleted;
        
        /// <remarks/>
        public event OperatePurOrderCompletedEventHandler OperatePurOrderCompleted;
        
        /// <remarks/>
        public event QueryWHCompletedEventHandler QueryWHCompleted;
        
        /// <remarks/>
        public event CalNextPurchaseCodeCompletedEventHandler CalNextPurchaseCodeCompleted;
        
        /// <remarks/>
        public event calNextWarehousingCodeCompletedEventHandler calNextWarehousingCodeCompleted;
        
        /// <remarks/>
        public event operateWarehousingRecordCompletedEventHandler operateWarehousingRecordCompleted;
        
        /// <remarks/>
        public event QueryWarehousingCompletedEventHandler QueryWarehousingCompleted;
        
        /// <remarks/>
        public event QuerySaleOrdersCompletedEventHandler QuerySaleOrdersCompleted;
        
        /// <remarks/>
        public event OperateSaleOrderCompletedEventHandler OperateSaleOrderCompleted;
        
        /// <remarks/>
        public event CalNextSaleOrderCodeCompletedEventHandler CalNextSaleOrderCodeCompleted;
        
        /// <remarks/>
        public event QuerySaleNotOutOrdersCompletedEventHandler QuerySaleNotOutOrdersCompleted;
        
        /// <remarks/>
        public event GenerateTestDataCompletedEventHandler GenerateTestDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/validateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool validateUser(string user, string pass) {
            object[] results = this.Invoke("validateUser", new object[] {
                        user,
                        pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validateUserAsync(string user, string pass) {
            this.validateUserAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void validateUserAsync(string user, string pass, object userState) {
            if ((this.validateUserOperationCompleted == null)) {
                this.validateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateUserOperationCompleted);
            }
            this.InvokeAsync("validateUser", new object[] {
                        user,
                        pass}, this.validateUserOperationCompleted, userState);
        }
        
        private void OnvalidateUserOperationCompleted(object arg) {
            if ((this.validateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateUserCompleted(this, new validateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryAllEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryAllEmployee() {
            object[] results = this.Invoke("QueryAllEmployee", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryAllEmployeeAsync() {
            this.QueryAllEmployeeAsync(null);
        }
        
        /// <remarks/>
        public void QueryAllEmployeeAsync(object userState) {
            if ((this.QueryAllEmployeeOperationCompleted == null)) {
                this.QueryAllEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryAllEmployeeOperationCompleted);
            }
            this.InvokeAsync("QueryAllEmployee", new object[0], this.QueryAllEmployeeOperationCompleted, userState);
        }
        
        private void OnQueryAllEmployeeOperationCompleted(object arg) {
            if ((this.QueryAllEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryAllEmployeeCompleted(this, new QueryAllEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteEmployeeByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteEmployeeByID(string EmployeeID) {
            object[] results = this.Invoke("DeleteEmployeeByID", new object[] {
                        EmployeeID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteEmployeeByIDAsync(string EmployeeID) {
            this.DeleteEmployeeByIDAsync(EmployeeID, null);
        }
        
        /// <remarks/>
        public void DeleteEmployeeByIDAsync(string EmployeeID, object userState) {
            if ((this.DeleteEmployeeByIDOperationCompleted == null)) {
                this.DeleteEmployeeByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteEmployeeByIDOperationCompleted);
            }
            this.InvokeAsync("DeleteEmployeeByID", new object[] {
                        EmployeeID}, this.DeleteEmployeeByIDOperationCompleted, userState);
        }
        
        private void OnDeleteEmployeeByIDOperationCompleted(object arg) {
            if ((this.DeleteEmployeeByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteEmployeeByIDCompleted(this, new DeleteEmployeeByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OperateEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int OperateEmployee(object[] param, int i) {
            object[] results = this.Invoke("OperateEmployee", new object[] {
                        param,
                        i});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void OperateEmployeeAsync(object[] param, int i) {
            this.OperateEmployeeAsync(param, i, null);
        }
        
        /// <remarks/>
        public void OperateEmployeeAsync(object[] param, int i, object userState) {
            if ((this.OperateEmployeeOperationCompleted == null)) {
                this.OperateEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOperateEmployeeOperationCompleted);
            }
            this.InvokeAsync("OperateEmployee", new object[] {
                        param,
                        i}, this.OperateEmployeeOperationCompleted, userState);
        }
        
        private void OnOperateEmployeeOperationCompleted(object arg) {
            if ((this.OperateEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OperateEmployeeCompleted(this, new OperateEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalNextEmployeeCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalNextEmployeeCode() {
            object[] results = this.Invoke("CalNextEmployeeCode", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalNextEmployeeCodeAsync() {
            this.CalNextEmployeeCodeAsync(null);
        }
        
        /// <remarks/>
        public void CalNextEmployeeCodeAsync(object userState) {
            if ((this.CalNextEmployeeCodeOperationCompleted == null)) {
                this.CalNextEmployeeCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalNextEmployeeCodeOperationCompleted);
            }
            this.InvokeAsync("CalNextEmployeeCode", new object[0], this.CalNextEmployeeCodeOperationCompleted, userState);
        }
        
        private void OnCalNextEmployeeCodeOperationCompleted(object arg) {
            if ((this.CalNextEmployeeCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalNextEmployeeCodeCompleted(this, new CalNextEmployeeCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryEmployeeByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryEmployeeByName(string staffName) {
            object[] results = this.Invoke("QueryEmployeeByName", new object[] {
                        staffName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryEmployeeByNameAsync(string staffName) {
            this.QueryEmployeeByNameAsync(staffName, null);
        }
        
        /// <remarks/>
        public void QueryEmployeeByNameAsync(string staffName, object userState) {
            if ((this.QueryEmployeeByNameOperationCompleted == null)) {
                this.QueryEmployeeByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryEmployeeByNameOperationCompleted);
            }
            this.InvokeAsync("QueryEmployeeByName", new object[] {
                        staffName}, this.QueryEmployeeByNameOperationCompleted, userState);
        }
        
        private void OnQueryEmployeeByNameOperationCompleted(object arg) {
            if ((this.QueryEmployeeByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryEmployeeByNameCompleted(this, new QueryEmployeeByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryCompanies", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryCompanies() {
            object[] results = this.Invoke("QueryCompanies", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryCompaniesAsync() {
            this.QueryCompaniesAsync(null);
        }
        
        /// <remarks/>
        public void QueryCompaniesAsync(object userState) {
            if ((this.QueryCompaniesOperationCompleted == null)) {
                this.QueryCompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryCompaniesOperationCompleted);
            }
            this.InvokeAsync("QueryCompanies", new object[0], this.QueryCompaniesOperationCompleted, userState);
        }
        
        private void OnQueryCompaniesOperationCompleted(object arg) {
            if ((this.QueryCompaniesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCompaniesCompleted(this, new QueryCompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OperaCompanies", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int OperaCompanies(object[] param, int i) {
            object[] results = this.Invoke("OperaCompanies", new object[] {
                        param,
                        i});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void OperaCompaniesAsync(object[] param, int i) {
            this.OperaCompaniesAsync(param, i, null);
        }
        
        /// <remarks/>
        public void OperaCompaniesAsync(object[] param, int i, object userState) {
            if ((this.OperaCompaniesOperationCompleted == null)) {
                this.OperaCompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOperaCompaniesOperationCompleted);
            }
            this.InvokeAsync("OperaCompanies", new object[] {
                        param,
                        i}, this.OperaCompaniesOperationCompleted, userState);
        }
        
        private void OnOperaCompaniesOperationCompleted(object arg) {
            if ((this.OperaCompaniesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OperaCompaniesCompleted(this, new OperaCompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryGoods", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryGoods() {
            object[] results = this.Invoke("QueryGoods", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryGoodsAsync() {
            this.QueryGoodsAsync(null);
        }
        
        /// <remarks/>
        public void QueryGoodsAsync(object userState) {
            if ((this.QueryGoodsOperationCompleted == null)) {
                this.QueryGoodsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryGoodsOperationCompleted);
            }
            this.InvokeAsync("QueryGoods", new object[0], this.QueryGoodsOperationCompleted, userState);
        }
        
        private void OnQueryGoodsOperationCompleted(object arg) {
            if ((this.QueryGoodsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryGoodsCompleted(this, new QueryGoodsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryGoodsByCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryGoodsByCode(string code) {
            object[] results = this.Invoke("QueryGoodsByCode", new object[] {
                        code});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryGoodsByCodeAsync(string code) {
            this.QueryGoodsByCodeAsync(code, null);
        }
        
        /// <remarks/>
        public void QueryGoodsByCodeAsync(string code, object userState) {
            if ((this.QueryGoodsByCodeOperationCompleted == null)) {
                this.QueryGoodsByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryGoodsByCodeOperationCompleted);
            }
            this.InvokeAsync("QueryGoodsByCode", new object[] {
                        code}, this.QueryGoodsByCodeOperationCompleted, userState);
        }
        
        private void OnQueryGoodsByCodeOperationCompleted(object arg) {
            if ((this.QueryGoodsByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryGoodsByCodeCompleted(this, new QueryGoodsByCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryGoodsByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryGoodsByName(string name) {
            object[] results = this.Invoke("QueryGoodsByName", new object[] {
                        name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryGoodsByNameAsync(string name) {
            this.QueryGoodsByNameAsync(name, null);
        }
        
        /// <remarks/>
        public void QueryGoodsByNameAsync(string name, object userState) {
            if ((this.QueryGoodsByNameOperationCompleted == null)) {
                this.QueryGoodsByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryGoodsByNameOperationCompleted);
            }
            this.InvokeAsync("QueryGoodsByName", new object[] {
                        name}, this.QueryGoodsByNameOperationCompleted, userState);
        }
        
        private void OnQueryGoodsByNameOperationCompleted(object arg) {
            if ((this.QueryGoodsByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryGoodsByNameCompleted(this, new QueryGoodsByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryGoodsByWarehouseID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryGoodsByWarehouseID(string param) {
            object[] results = this.Invoke("QueryGoodsByWarehouseID", new object[] {
                        param});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryGoodsByWarehouseIDAsync(string param) {
            this.QueryGoodsByWarehouseIDAsync(param, null);
        }
        
        /// <remarks/>
        public void QueryGoodsByWarehouseIDAsync(string param, object userState) {
            if ((this.QueryGoodsByWarehouseIDOperationCompleted == null)) {
                this.QueryGoodsByWarehouseIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryGoodsByWarehouseIDOperationCompleted);
            }
            this.InvokeAsync("QueryGoodsByWarehouseID", new object[] {
                        param}, this.QueryGoodsByWarehouseIDOperationCompleted, userState);
        }
        
        private void OnQueryGoodsByWarehouseIDOperationCompleted(object arg) {
            if ((this.QueryGoodsByWarehouseIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryGoodsByWarehouseIDCompleted(this, new QueryGoodsByWarehouseIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryAllProductInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryAllProductInfo() {
            object[] results = this.Invoke("QueryAllProductInfo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryAllProductInfoAsync() {
            this.QueryAllProductInfoAsync(null);
        }
        
        /// <remarks/>
        public void QueryAllProductInfoAsync(object userState) {
            if ((this.QueryAllProductInfoOperationCompleted == null)) {
                this.QueryAllProductInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryAllProductInfoOperationCompleted);
            }
            this.InvokeAsync("QueryAllProductInfo", new object[0], this.QueryAllProductInfoOperationCompleted, userState);
        }
        
        private void OnQueryAllProductInfoOperationCompleted(object arg) {
            if ((this.QueryAllProductInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryAllProductInfoCompleted(this, new QueryAllProductInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OperateProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int OperateProduct(object[] param, int op) {
            object[] results = this.Invoke("OperateProduct", new object[] {
                        param,
                        op});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void OperateProductAsync(object[] param, int op) {
            this.OperateProductAsync(param, op, null);
        }
        
        /// <remarks/>
        public void OperateProductAsync(object[] param, int op, object userState) {
            if ((this.OperateProductOperationCompleted == null)) {
                this.OperateProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOperateProductOperationCompleted);
            }
            this.InvokeAsync("OperateProduct", new object[] {
                        param,
                        op}, this.OperateProductOperationCompleted, userState);
        }
        
        private void OnOperateProductOperationCompleted(object arg) {
            if ((this.OperateProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OperateProductCompleted(this, new OperateProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalNextProductCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalNextProductCode() {
            object[] results = this.Invoke("CalNextProductCode", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalNextProductCodeAsync() {
            this.CalNextProductCodeAsync(null);
        }
        
        /// <remarks/>
        public void CalNextProductCodeAsync(object userState) {
            if ((this.CalNextProductCodeOperationCompleted == null)) {
                this.CalNextProductCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalNextProductCodeOperationCompleted);
            }
            this.InvokeAsync("CalNextProductCode", new object[0], this.CalNextProductCodeOperationCompleted, userState);
        }
        
        private void OnCalNextProductCodeOperationCompleted(object arg) {
            if ((this.CalNextProductCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalNextProductCodeCompleted(this, new CalNextProductCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryPurOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryPurOrder(string state) {
            object[] results = this.Invoke("QueryPurOrder", new object[] {
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryPurOrderAsync(string state) {
            this.QueryPurOrderAsync(state, null);
        }
        
        /// <remarks/>
        public void QueryPurOrderAsync(string state, object userState) {
            if ((this.QueryPurOrderOperationCompleted == null)) {
                this.QueryPurOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryPurOrderOperationCompleted);
            }
            this.InvokeAsync("QueryPurOrder", new object[] {
                        state}, this.QueryPurOrderOperationCompleted, userState);
        }
        
        private void OnQueryPurOrderOperationCompleted(object arg) {
            if ((this.QueryPurOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryPurOrderCompleted(this, new QueryPurOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryPurNotInOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryPurNotInOrder() {
            object[] results = this.Invoke("QueryPurNotInOrder", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryPurNotInOrderAsync() {
            this.QueryPurNotInOrderAsync(null);
        }
        
        /// <remarks/>
        public void QueryPurNotInOrderAsync(object userState) {
            if ((this.QueryPurNotInOrderOperationCompleted == null)) {
                this.QueryPurNotInOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryPurNotInOrderOperationCompleted);
            }
            this.InvokeAsync("QueryPurNotInOrder", new object[0], this.QueryPurNotInOrderOperationCompleted, userState);
        }
        
        private void OnQueryPurNotInOrderOperationCompleted(object arg) {
            if ((this.QueryPurNotInOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryPurNotInOrderCompleted(this, new QueryPurNotInOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryPurOrderByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryPurOrderByID(string orderId) {
            object[] results = this.Invoke("QueryPurOrderByID", new object[] {
                        orderId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryPurOrderByIDAsync(string orderId) {
            this.QueryPurOrderByIDAsync(orderId, null);
        }
        
        /// <remarks/>
        public void QueryPurOrderByIDAsync(string orderId, object userState) {
            if ((this.QueryPurOrderByIDOperationCompleted == null)) {
                this.QueryPurOrderByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryPurOrderByIDOperationCompleted);
            }
            this.InvokeAsync("QueryPurOrderByID", new object[] {
                        orderId}, this.QueryPurOrderByIDOperationCompleted, userState);
        }
        
        private void OnQueryPurOrderByIDOperationCompleted(object arg) {
            if ((this.QueryPurOrderByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryPurOrderByIDCompleted(this, new QueryPurOrderByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OperatePurOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int OperatePurOrder(object[] param, int op) {
            object[] results = this.Invoke("OperatePurOrder", new object[] {
                        param,
                        op});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void OperatePurOrderAsync(object[] param, int op) {
            this.OperatePurOrderAsync(param, op, null);
        }
        
        /// <remarks/>
        public void OperatePurOrderAsync(object[] param, int op, object userState) {
            if ((this.OperatePurOrderOperationCompleted == null)) {
                this.OperatePurOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOperatePurOrderOperationCompleted);
            }
            this.InvokeAsync("OperatePurOrder", new object[] {
                        param,
                        op}, this.OperatePurOrderOperationCompleted, userState);
        }
        
        private void OnOperatePurOrderOperationCompleted(object arg) {
            if ((this.OperatePurOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OperatePurOrderCompleted(this, new OperatePurOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryWH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryWH() {
            object[] results = this.Invoke("QueryWH", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryWHAsync() {
            this.QueryWHAsync(null);
        }
        
        /// <remarks/>
        public void QueryWHAsync(object userState) {
            if ((this.QueryWHOperationCompleted == null)) {
                this.QueryWHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryWHOperationCompleted);
            }
            this.InvokeAsync("QueryWH", new object[0], this.QueryWHOperationCompleted, userState);
        }
        
        private void OnQueryWHOperationCompleted(object arg) {
            if ((this.QueryWHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryWHCompleted(this, new QueryWHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalNextPurchaseCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalNextPurchaseCode() {
            object[] results = this.Invoke("CalNextPurchaseCode", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalNextPurchaseCodeAsync() {
            this.CalNextPurchaseCodeAsync(null);
        }
        
        /// <remarks/>
        public void CalNextPurchaseCodeAsync(object userState) {
            if ((this.CalNextPurchaseCodeOperationCompleted == null)) {
                this.CalNextPurchaseCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalNextPurchaseCodeOperationCompleted);
            }
            this.InvokeAsync("CalNextPurchaseCode", new object[0], this.CalNextPurchaseCodeOperationCompleted, userState);
        }
        
        private void OnCalNextPurchaseCodeOperationCompleted(object arg) {
            if ((this.CalNextPurchaseCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalNextPurchaseCodeCompleted(this, new CalNextPurchaseCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/calNextWarehousingCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string calNextWarehousingCode() {
            object[] results = this.Invoke("calNextWarehousingCode", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void calNextWarehousingCodeAsync() {
            this.calNextWarehousingCodeAsync(null);
        }
        
        /// <remarks/>
        public void calNextWarehousingCodeAsync(object userState) {
            if ((this.calNextWarehousingCodeOperationCompleted == null)) {
                this.calNextWarehousingCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalNextWarehousingCodeOperationCompleted);
            }
            this.InvokeAsync("calNextWarehousingCode", new object[0], this.calNextWarehousingCodeOperationCompleted, userState);
        }
        
        private void OncalNextWarehousingCodeOperationCompleted(object arg) {
            if ((this.calNextWarehousingCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calNextWarehousingCodeCompleted(this, new calNextWarehousingCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/operateWarehousingRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int operateWarehousingRecord(object[] param, int op) {
            object[] results = this.Invoke("operateWarehousingRecord", new object[] {
                        param,
                        op});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void operateWarehousingRecordAsync(object[] param, int op) {
            this.operateWarehousingRecordAsync(param, op, null);
        }
        
        /// <remarks/>
        public void operateWarehousingRecordAsync(object[] param, int op, object userState) {
            if ((this.operateWarehousingRecordOperationCompleted == null)) {
                this.operateWarehousingRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnoperateWarehousingRecordOperationCompleted);
            }
            this.InvokeAsync("operateWarehousingRecord", new object[] {
                        param,
                        op}, this.operateWarehousingRecordOperationCompleted, userState);
        }
        
        private void OnoperateWarehousingRecordOperationCompleted(object arg) {
            if ((this.operateWarehousingRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.operateWarehousingRecordCompleted(this, new operateWarehousingRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryWarehousing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryWarehousing(object[] param, int op) {
            object[] results = this.Invoke("QueryWarehousing", new object[] {
                        param,
                        op});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryWarehousingAsync(object[] param, int op) {
            this.QueryWarehousingAsync(param, op, null);
        }
        
        /// <remarks/>
        public void QueryWarehousingAsync(object[] param, int op, object userState) {
            if ((this.QueryWarehousingOperationCompleted == null)) {
                this.QueryWarehousingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryWarehousingOperationCompleted);
            }
            this.InvokeAsync("QueryWarehousing", new object[] {
                        param,
                        op}, this.QueryWarehousingOperationCompleted, userState);
        }
        
        private void OnQueryWarehousingOperationCompleted(object arg) {
            if ((this.QueryWarehousingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryWarehousingCompleted(this, new QueryWarehousingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QuerySaleOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QuerySaleOrders(string state) {
            object[] results = this.Invoke("QuerySaleOrders", new object[] {
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QuerySaleOrdersAsync(string state) {
            this.QuerySaleOrdersAsync(state, null);
        }
        
        /// <remarks/>
        public void QuerySaleOrdersAsync(string state, object userState) {
            if ((this.QuerySaleOrdersOperationCompleted == null)) {
                this.QuerySaleOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySaleOrdersOperationCompleted);
            }
            this.InvokeAsync("QuerySaleOrders", new object[] {
                        state}, this.QuerySaleOrdersOperationCompleted, userState);
        }
        
        private void OnQuerySaleOrdersOperationCompleted(object arg) {
            if ((this.QuerySaleOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySaleOrdersCompleted(this, new QuerySaleOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OperateSaleOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int OperateSaleOrder(object[] param, int op) {
            object[] results = this.Invoke("OperateSaleOrder", new object[] {
                        param,
                        op});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void OperateSaleOrderAsync(object[] param, int op) {
            this.OperateSaleOrderAsync(param, op, null);
        }
        
        /// <remarks/>
        public void OperateSaleOrderAsync(object[] param, int op, object userState) {
            if ((this.OperateSaleOrderOperationCompleted == null)) {
                this.OperateSaleOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOperateSaleOrderOperationCompleted);
            }
            this.InvokeAsync("OperateSaleOrder", new object[] {
                        param,
                        op}, this.OperateSaleOrderOperationCompleted, userState);
        }
        
        private void OnOperateSaleOrderOperationCompleted(object arg) {
            if ((this.OperateSaleOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OperateSaleOrderCompleted(this, new OperateSaleOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalNextSaleOrderCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalNextSaleOrderCode() {
            object[] results = this.Invoke("CalNextSaleOrderCode", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalNextSaleOrderCodeAsync() {
            this.CalNextSaleOrderCodeAsync(null);
        }
        
        /// <remarks/>
        public void CalNextSaleOrderCodeAsync(object userState) {
            if ((this.CalNextSaleOrderCodeOperationCompleted == null)) {
                this.CalNextSaleOrderCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalNextSaleOrderCodeOperationCompleted);
            }
            this.InvokeAsync("CalNextSaleOrderCode", new object[0], this.CalNextSaleOrderCodeOperationCompleted, userState);
        }
        
        private void OnCalNextSaleOrderCodeOperationCompleted(object arg) {
            if ((this.CalNextSaleOrderCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalNextSaleOrderCodeCompleted(this, new CalNextSaleOrderCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QuerySaleNotOutOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QuerySaleNotOutOrders() {
            object[] results = this.Invoke("QuerySaleNotOutOrders", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QuerySaleNotOutOrdersAsync() {
            this.QuerySaleNotOutOrdersAsync(null);
        }
        
        /// <remarks/>
        public void QuerySaleNotOutOrdersAsync(object userState) {
            if ((this.QuerySaleNotOutOrdersOperationCompleted == null)) {
                this.QuerySaleNotOutOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySaleNotOutOrdersOperationCompleted);
            }
            this.InvokeAsync("QuerySaleNotOutOrders", new object[0], this.QuerySaleNotOutOrdersOperationCompleted, userState);
        }
        
        private void OnQuerySaleNotOutOrdersOperationCompleted(object arg) {
            if ((this.QuerySaleNotOutOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySaleNotOutOrdersCompleted(this, new QuerySaleNotOutOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerateTestData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerateTestData() {
            this.Invoke("GenerateTestData", new object[0]);
        }
        
        /// <remarks/>
        public void GenerateTestDataAsync() {
            this.GenerateTestDataAsync(null);
        }
        
        /// <remarks/>
        public void GenerateTestDataAsync(object userState) {
            if ((this.GenerateTestDataOperationCompleted == null)) {
                this.GenerateTestDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateTestDataOperationCompleted);
            }
            this.InvokeAsync("GenerateTestData", new object[0], this.GenerateTestDataOperationCompleted, userState);
        }
        
        private void OnGenerateTestDataOperationCompleted(object arg) {
            if ((this.GenerateTestDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateTestDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void validateUserCompletedEventHandler(object sender, validateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryAllEmployeeCompletedEventHandler(object sender, QueryAllEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryAllEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryAllEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteEmployeeByIDCompletedEventHandler(object sender, DeleteEmployeeByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteEmployeeByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteEmployeeByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void OperateEmployeeCompletedEventHandler(object sender, OperateEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperateEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OperateEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CalNextEmployeeCodeCompletedEventHandler(object sender, CalNextEmployeeCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalNextEmployeeCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalNextEmployeeCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryEmployeeByNameCompletedEventHandler(object sender, QueryEmployeeByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryEmployeeByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryEmployeeByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryCompaniesCompletedEventHandler(object sender, QueryCompaniesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void OperaCompaniesCompletedEventHandler(object sender, OperaCompaniesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperaCompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OperaCompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryGoodsCompletedEventHandler(object sender, QueryGoodsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryGoodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryGoodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryGoodsByCodeCompletedEventHandler(object sender, QueryGoodsByCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryGoodsByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryGoodsByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryGoodsByNameCompletedEventHandler(object sender, QueryGoodsByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryGoodsByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryGoodsByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryGoodsByWarehouseIDCompletedEventHandler(object sender, QueryGoodsByWarehouseIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryGoodsByWarehouseIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryGoodsByWarehouseIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryAllProductInfoCompletedEventHandler(object sender, QueryAllProductInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryAllProductInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryAllProductInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void OperateProductCompletedEventHandler(object sender, OperateProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperateProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OperateProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CalNextProductCodeCompletedEventHandler(object sender, CalNextProductCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalNextProductCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalNextProductCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryPurOrderCompletedEventHandler(object sender, QueryPurOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryPurOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryPurOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryPurNotInOrderCompletedEventHandler(object sender, QueryPurNotInOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryPurNotInOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryPurNotInOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryPurOrderByIDCompletedEventHandler(object sender, QueryPurOrderByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryPurOrderByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryPurOrderByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void OperatePurOrderCompletedEventHandler(object sender, OperatePurOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperatePurOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OperatePurOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryWHCompletedEventHandler(object sender, QueryWHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryWHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryWHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CalNextPurchaseCodeCompletedEventHandler(object sender, CalNextPurchaseCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalNextPurchaseCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalNextPurchaseCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void calNextWarehousingCodeCompletedEventHandler(object sender, calNextWarehousingCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calNextWarehousingCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calNextWarehousingCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void operateWarehousingRecordCompletedEventHandler(object sender, operateWarehousingRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class operateWarehousingRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal operateWarehousingRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryWarehousingCompletedEventHandler(object sender, QueryWarehousingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryWarehousingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryWarehousingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QuerySaleOrdersCompletedEventHandler(object sender, QuerySaleOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySaleOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerySaleOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void OperateSaleOrderCompletedEventHandler(object sender, OperateSaleOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperateSaleOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OperateSaleOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CalNextSaleOrderCodeCompletedEventHandler(object sender, CalNextSaleOrderCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalNextSaleOrderCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalNextSaleOrderCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QuerySaleNotOutOrdersCompletedEventHandler(object sender, QuerySaleNotOutOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySaleNotOutOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerySaleNotOutOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GenerateTestDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591